"""Add job posting stats

Revision ID: 8d79f9e833b5
Revises: 991ecb2bf269
Create Date: 2025-07-23 21:43:55.594748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d79f9e833b5'
down_revision = '991ecb2bf269'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_posting_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('standard_job_id', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=True),
    sa.Column('min_days', sa.Float(), nullable=True),
    sa.Column('avg_days', sa.Float(), nullable=True),
    sa.Column('max_days', sa.Float(), nullable=True),
    sa.Column('job_postings_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_posting_stats', schema='public')
    # ### end Alembic commands ###
